# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
locale               : "en-US"
lang                 : en # the language of your site (for example: en, fr, cn, ru, etc.)
last_updated         : true # set to true if you want to display last updated in the footer
date_format          : "%Y-%m-%d"
#baseurl              : /profile # the subpath of your site, e.g. /blog/. Leave blank for root

title                : "Jaekwon Lee"
#subtitle             : "sub title of the website"

#logo                : "/assets/imgs/88x88.png"
#masthead_title      : "My Custom Title"


# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------
# theme setting for Github pages
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# theme setting for local
#theme                   : minimal-mistakes-jekyll

minimal_mistakes_skin   : "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
#repository              : ""

# -----------------------------------------------------------------------------
# Layout and common contents settings
# -----------------------------------------------------------------------------
search: false

# remove feed icon
atom_feed:
  hide: true

# default values for each type or layouts
defaults:
  # home pages
  - scope:
      path: ""
      type: pages
    values:
#      layout: home     # this default settings can be applied to each layout
#      layout: single
      show_date: true
      author_profile: true
  # posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      comments: true
      author_profile: false       # This is not working....
      paginate: 10 # amount of posts to show
      paginate_path: /page:num/

#header:
#  image: /assets/images/unsplash-image-1.jpg
#  image_description: "A description of the image"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/exatoa"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar fa-fw"     # applied "fa-fw" style
      url: "https://scholar.google.com/citations?user=EDpccDkAAAAJ&hl=en"


# Custom data for this site
credits:
  - name: Jekyll
    url: https://jekyllrb.com
  - name: Minimal Mistakes
    url: https://mademistakes.com/work/minimal-mistakes-jekyll-theme/
  - name: Academicons
    url: https://jpswalsh.github.io/academicons/


# -----------------------------------------------------------------------------
# Author settings
# -----------------------------------------------------------------------------
author: Jaekwon Lee


# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------
#source              : ./contents/   # if it is changed, Github Pages would not work correctly...
#destination         : ./_site
#collections_dir     : .
#plugins_dir         : _plugins # takes an array of strings and loads plugins in that order
#layouts_dir         : _layouts
#data_dir            : _data
#includes_dir        : contents
#include:
#  - contents
#  - files
exclude:
  - Vagrantfile
  - Gemfile
  - Gemfile.lock
  - service.sh
  - README.md

# Markdown and syntax highlight
lsi: false
incremental: false
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1


# Plug-ins
plugins:
#  - jekyll-relative-links
#  - jekyll-archives
#  - jekyll-email-protect
  - jekyll-feed
#  - jekyll-get-json
#  - jekyll-imagemagick
#  - jekyll-jupyter-notebook
#  - jekyll-link-attributes
#  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll/scholar
  - jekyll-sitemap
#  - jekyll-toc
#  - jekyll-twitter-plugin
#  - jemoji
  - jekyll-include-cache


#relative_links:
#  enabled: true
#  collections: true
